### PR TITLE
Add fstart argument to write_line

### PR DESCRIPTION
**Pull request by janmalec**
It is needed to control how the pendf files are put together. Just like fend, which is already implemented.

### CODE REVIEW

**Comment by luca-fiorito-11** [comment]
It makes sense. 
However, any addition to the code requires its own test in the docstring. Can you add it?
Also, FEND is ENDF6 nomenclature. Can you check if fstart is part of the default nomenclature?
If no indication is given in the endf6 manual, then we can accept fstart

**Comment by janmalec** [comment]
I changed FSTART to TPID, which is ENDF6 nomenclature and added docstring tests.

**Review by luca-fiorito-11 — APPROVED** [review]

**Comment by luca-fiorito-11** [comment]
You submitted two items to the same PR. Can you submit two PRs instead?

**Comment by luca-fiorito-11** [comment]
@janmalec , the test failed. Can you check it?

**Pull request merged**
