### PR TITLE
Lbarone

### PR DESCRIPTION
**Pull request by Luiigi99**
Test of a pull request but the new file Nubar_Pu239 is already competed.

### CODE REVIEW

**Review by luca-fiorito-11 — CHANGES_REQUESTED** [review]
Please, delete all cell outputs and resubmit it.
Then I'll review it!

**Comment by Luiigi99** [comment]
Done!

**Comment by Luiigi99** [comment]
I added the modified samples functions for the standard deviation convergence

**Comment by Luiigi99** [comment]
Deleted the last commit in order to separate them

**Comment by luca-fiorito-11** [comment]
inactive

**Pull request closed without merging**
